USE [master]
GO
/****** Object:  Database [SotexHackathon]    Script Date: 18. 4. 2026. 13:40:50 ******/
CREATE DATABASE [SotexHackathon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SotexHackathon', FILENAME = N'/var/opt/mssql/data/SotexHackathon_Primary.mdf' , SIZE = 1253376KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SotexHackathon_log', FILENAME = N'/var/opt/mssql/data/SotexHackathon_Primary.ldf' , SIZE = 860160KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SotexHackathon] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SotexHackathon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SotexHackathon] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SotexHackathon] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SotexHackathon] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SotexHackathon] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SotexHackathon] SET ARITHABORT OFF 
GO
ALTER DATABASE [SotexHackathon] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SotexHackathon] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SotexHackathon] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SotexHackathon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SotexHackathon] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SotexHackathon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SotexHackathon] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SotexHackathon] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SotexHackathon] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SotexHackathon] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SotexHackathon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SotexHackathon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SotexHackathon] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SotexHackathon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SotexHackathon] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SotexHackathon] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SotexHackathon] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SotexHackathon] SET RECOVERY FULL 
GO
ALTER DATABASE [SotexHackathon] SET  MULTI_USER 
GO
ALTER DATABASE [SotexHackathon] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SotexHackathon] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SotexHackathon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SotexHackathon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SotexHackathon] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SotexHackathon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SotexHackathon', N'ON'
GO
ALTER DATABASE [SotexHackathon] SET QUERY_STORE = ON
GO
ALTER DATABASE [SotexHackathon] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SotexHackathon]
GO
/****** Object:  Table [dbo].[Channels]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Channels](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Unit] [nvarchar](30) NULL,
 CONSTRAINT [PK_Channels] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DistributionSubstation]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DistributionSubstation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[MeterId] [int] NULL,
	[Feeder11Id] [int] NULL,
	[Feeder33Id] [int] NULL,
	[NameplateRating] [int] NULL,
	[Latitude] [decimal](12, 9) NULL,
	[Longitude] [decimal](12, 9) NULL,
 CONSTRAINT [PK_DistributionSubstation] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feeder33Substation]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feeder33Substation](
	[Feeders33Id] [int] NOT NULL,
	[SubstationsId] [int] NOT NULL,
 CONSTRAINT [PK_Feeder33Substation] PRIMARY KEY CLUSTERED 
(
	[Feeders33Id] ASC,
	[SubstationsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feeders11]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feeders11](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[SsId] [int] NULL,
	[MeterId] [int] NULL,
	[Feeder33Id] [int] NULL,
	[NameplateRating] [int] NULL,
	[TsId] [int] NULL,
 CONSTRAINT [PK_Feeders11] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feeders33]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feeders33](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[TsId] [int] NULL,
	[IsDeleted] [bit] NOT NULL,
	[MeterId] [int] NULL,
	[NameplateRating] [int] NULL,
 CONSTRAINT [PK_Feeders33] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MeterReads]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MeterReads](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Mid] [int] NOT NULL,
	[Val] [float] NOT NULL,
	[Ts] [datetime2](7) NOT NULL,
	[Cid] [int] NOT NULL,
 CONSTRAINT [PK_MeterReads] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[Ts] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MeterReadTfes]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MeterReadTfes](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Mid] [int] NOT NULL,
	[Val] [float] NOT NULL,
	[Ts] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_MeterReadTfes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[Ts] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Meters]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Meters](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MSN] [nvarchar](40) NULL,
	[MultiplierFactor] [float] NOT NULL,
 CONSTRAINT [PK_Meters] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Substations]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Substations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Latitude] [decimal](12, 9) NULL,
	[Longitude] [decimal](12, 9) NULL,
 CONSTRAINT [PK_Substations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TransmissionStations]    Script Date: 18. 4. 2026. 13:40:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TransmissionStations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Latitude] [decimal](12, 9) NULL,
	[Longitude] [decimal](12, 9) NULL,
 CONSTRAINT [PK_TransmissionStations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SotexHackathon] SET  READ_WRITE 
GO
